apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-segmenter
  namespace: ecom
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ecom-user-segmenter
        version: v1
    spec:
      containers:
      - name: user-segmenter
        image: khurlbut/user-segmenter:v1
        env:
        - name: SEGMENTATION_HOST
          #service-user-segmenter.ecom.svc.cluster.local
          value: "http://service-segmenter.ecom.svc.cluster.local:8080"
        - name: REDIRECT_PROTOCOL
          value: "http"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        imagePullPolicy: Always #IfNotPresent
        command: ["npm"]
        args: ["run", "start"]
        ports:
        - containerPort: 3000