apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-home
spec:
  hosts:
  - "*"
  gateways:
   - gateway-home
  http:

  # location '/browse/home.do' with cookies initialized
  - match:
    - headers:
        cookie:
          regex: (^|.*;\s)unknownShopperId=.* 
      uri:
          prefix: /browse/home.do
    route:
     - destination:
         host: service-home.ecom.svc.cluster.local
    appendHeaders:
        'Someheader': 'value' 

  # location '/' with cookies initialized
  - match:
    - headers:
        cookie:
          regex: (^|.*;\s)unknownShopperId=.* 
      uri:
          exact: /
    rewrite:
      uri: /browse/home.do
    route:
     - destination:
         host: service-home.ecom.svc.cluster.local
    appendHeaders:
        'Someheader': 'value' 

  # cookies not initialized 
  - route:
      - destination:
          host: service-user-segmenter.ecom.svc.cluster.local