apiVersion: v1
kind: ConfigMap
metadata:
  name: config-segmenter
  namespace: ecom
  labels:
    app: ecom
data:
  config.json: | 
    {
      "IPAddress": "127.0.0.1",
      "Port": "8080",
      "Pages": [ {
                    "Path":"*", 
                    "Status": 200, 
                    "InjectionKeys": ["path"],
                    "Body": "{\"%s\": [{\"allBrandsAllPages\":\"components\"}]}"
      } ]
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: segmenter
  namespace: ecom
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ecom-segmenter
        version: v1
    spec:
      containers:
      - name: segmenter
        image: khurlbut/fakeserver:v1
        imagePullPolicy: Always #IfNotPresent
        command:
        - fakeserver
        - --config-file=/config/config.json
        volumeMounts:
          - name: config
            mountPath: /config
        ports:
        - containerPort: 8080
      volumes:
      - name: config
        configMap:
          name: "config-segmenter"   